server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: upgy1dh0vtthrryh
    password: 5wcgZRpbL9SQcB9koeKw
    url: jdbc:mysql://bdapn9vicgthodllp7lk-mysql.services.clever-cloud.com:3306/bdapn9vicgthodllp7lk
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
