server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ukyp9pvflugzipfl
    password: 8zXkq4H2iomlTKrrQ50j
    url: jdbc:mysql://b5mpannz2inuotpj8yw4-mysql.services.clever-cloud.com/b5mpannz2inuotpj8yw4
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
