server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: uqqj0i9tsornqxuc
    password: yNp0l9UE81BZqJ7Nrmo3
    url: jdbc:mysql://bacenhq4uxqclklsdlbb-mysql.services.clever-cloud.com/bacenhq4uxqclklsdlbb
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
