server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ueiq1cyesq90h6h5
    password: Wo4pKCkx2sV3yIzDtqE8
    url: jdbc:mysql://b3fmu8rmiybec5shkrsb-mysql.services.clever-cloud.com:3306/b3fmu8rmiybec5shkrsb
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
